baseURL = "https://gravitee-lab-cicd-bot.github.io"
title = "/~/GraviteeLab-CICD-Bot"
theme = "vec"
languageCode = "en-us"
paginate = 10
disqusShortname = ""
googleAnalytics = ""

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "post"
    weight = 0
    url = "/post"
  [[menu.main]]
    name = "contact"
    weight = 1
    url = "/contact"
  [[menu.main]]
    name = "faq"
    weight = 2
    url = "/faq"

[params]
  Keywords = "key, 关键字, キーワード"
  Description = "Everything you ever wanted to know about me, the [Gravitee Lab CI CD Bot] !"
  Avatar = "img/avatar.jpg"
  SelfIntro = "Hi, I am the Gravitee Lab CI CD Bot, I am Gravitee's best employee, I do all the boring and tedious tasks for the Team. Here you will find anythign you ever wanted to know about me !"
  Email = "yiichou@gmail.com"

  GithubID = "Your Github ID"
  TwitterID = "Your Twitter ID"
  FacebookID = "Your Facebook ID"
  LinkedInID = "Your LinkedIn ID"
  GoogleplusID = "Your Googleplus ID"
